### ISSUE TITLE
Can't input Chinese or Japanese after a default schema node

### ISSUE THREAD

**Issue by ximing** [ProseMirror/website#72] opened 2017-10-12 09:04 UTC
1, clone ProseMirror/website
2, change pages/examples/dino/example.js content  as below

<img width="706" alt="qq20171012-162406 2x" src="https://user-images.githubusercontent.com/4659887/31486367-de57fe2c-aefc-11e7-948a-4409fbfa6c64.png">
code is

```
const dinoNodeSpec = {
  attrs: {type: {default: "brontosaurus"}},
  inline: true,
  group: "inline",
  draggable: true,
  atom: true,
  toDOM: node => [
      'span',
      '@' + node.attrs.type
  ],
  parseDOM: [{
    tag: "img[dino-type]",
    getAttrs: dom => {
      let type = dom.getAttribute("dino-type")
      return dinos.indexOf(type) > -1 ? {type} : false
    }
  }]
}
```

Some input problems are shown below：

![bug](https://user-images.githubusercontent.com/4659887/31487382-0cb5cf44-af00-11e7-9a37-533e42506503.gif)

Input is interrupted，Input method disappear，temp content is selected. And Can't continue to input anything(both Chinese and English).Looks like the editor loses focus

English can be entered normally, Chinese and Japanese will not work。

But， when dinoNodeSpec return `["img", {src: "/img/dino/" + node.attrs.type + ".png"}]`,there is no problem, you can normally enter.
Is there any problem with my code?

I use mac and browser is chrome(Version 61.0.3163.100 (Official Build) (64-bit));
I use a MAC's own input method。
System Preferences / Keyboard / Input Sources
Add Japanese and Pinyin-Simplified 

<img width="665" alt="qq20171012-165438 2x" src="https://user-images.githubusercontent.com/4659887/31487808-515a8f1c-af01-11e7-98be-accb04ea1f52.png">

**Comment by marijnh** [comment] 2017-10-12 09:37
> Is there any problem with my code?

No, this is in principle something that ProseMirror supports. The issue seems to be a browser bug in Chrome. Even without ProseMirror, if I create a plain contentEditable element with some text and a `contentEditable=false` span inside of it, IME seems to be completely broken after that element. In Firefox, everything seems to work fine.

It's sometimes possible that you can tweak the HTML or CSS of your elements in some way to work around issues like this, but I didn't manage to find such a solution for this one (making the span `display: inline-block`, which has often worked for other kinds of cursor issues, didn't help).

So probably the only recourse is to report this as a Chrome bug and hope someone does something about it. Note that you can give the HTML below as reproducing example (i.e. you don't need to complicate the issue with ProseMirror):

```
<div contenteditable=true>
  <p>Put the cursor after this element: <span contenteditable=false>ABC</span> and IME breaks (Chrome 59)</p>
</div>
```

**Comment by ximing** [comment] 2017-10-12 10:14
thx！I will report bugs to the chrome team

**Comment by ximing** [comment] 2017-10-17 04:16
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=775013

**Comment by marijnh** [comment] 2017-10-17 06:19
Thanks for filing the issue! Let's hope it sees a response.

**Comment by marijnh** [comment] 2017-10-18 12:32
Going to close this here, since it is not really related to the ProseMirror website.

**Closed by marijnh** 2017-10-18 12:32 UTC
